name: Deploy Snowpark CLI Execution
on:
  push:
    branches:
      - "*"
    tags:
      - "v*"
  workflow_dispatch:

env:
  SNOWFLAKE_CONNECTIONS_MYCONNECTION_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }} # Add these secerts to github repository
  SNOWFLAKE_CONNECTIONS_MYCONNECTION_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }} # Add these secerts to github repository
  SNOWFLAKE_CONNECTIONS_MYCONNECTION_USER: ${{ secrets.SNOWFLAKE_USER }} # Add these secerts to github repository
  SNOWFLAKE_CONNECTIONS_MYCONNECTION_DATABASE: 'DATASCIENCE'
  SNOWFLAKE_CONNECTIONS_MYCONNECTION_SCHEMA: 'CUSTOM_FUNCTIONS'
  SNOWFLAKE_CONNECTIONS_MYCONNECTION_WAREHOUSE: 'DS_WH_XS'
  SNOWFLAKE_CONNECTIONS_MYCONNECTION_ROLE: 'DATA_SCIENTIST'

jobs:
  pytest:
    name: Pytest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          pip install .
          pip install pytest pytest-cov

      - name: Run pytest
        run: |
          coverage run -m pytest
          coverage report --precision=2
          coverage xml

  snowflake-cli:
    needs: pytest
    name: Snowflake CLI
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install Snowflake CLI
        uses: Snowflake-Labs/snowflake-cli-action@v1
        with:
          cli-version: "latest"
          default-config-file-path: "./config.toml"
        
      - name: Test Snowflake CLI
        id: TestSnowClI
        run: |
          snow --version
          snow connection set-default "myconnection"
          snow connection test

      - name: Deploy Functions and Procedures
        id: deploy
        run: |
            snow snowpark build
            snow snowpark deploy --replace

      - name: Run Aggregation Function Example
        id: runaggregation
        run: |
          snow sql -q "SELECT * FROM DATASCIENCE.CUSTOM_FUNCTIONS.ORDERS LIMIT 2"
          snow sql -f ./customfunctions/files/perform_aggregation.sql
          snow sql -q "SELECT * FROM DATASCIENCE.CUSTOM_FUNCTIONS.ORDERS_AGGREGATES LIMIT 2"
          now sql -f ./customfunctions/files/perform_aggregation_config.sql -D SOURCE_TABLE=DATASCIENCE.CUSTOM_FUNCTIONS.ORDERS -D TARGET_TABLE=DATASCIENCE.CUSTOM_FUNCTIONS.ORDERS_AGGREGATES
          snow sql -q "SELECT * FROM DATASCIENCE.CUSTOM_FUNCTIONS.ORDERS_AGGREGATES LIMIT 2"