"""Helps Manage Snowflake Connection"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_common.ipynb.

# %% auto 0
__all__ = ['print_hello', 'is_snowflake_environment', 'find_config_file', 'get_config_path', 'load_config']

# %% ../nbs/01_common.ipynb 3
from pathlib import Path

from typing import Optional, Dict
import sys
import json
import os
import yaml
import logging
import zipfile

# %% ../nbs/01_common.ipynb 4
def print_hello(name: str) -> str:
    """
    Prints a greeting message for the specified name. DEFAULT FUNCTION

    Parameters
    ----------
    name : str
        The name of the person to greet.

    Returns
    -------
    str
        A greeting message for the provided
    """
    return f"Hello {name}!"



# %% ../nbs/01_common.ipynb 6
def is_snowflake_environment() -> bool:
    """Detect if code is running in Snowflake environment."""
    return hasattr(sys, '_xoptions') and 'snowflake_import_directory' in sys._xoptions


# %% ../nbs/01_common.ipynb 8
def find_config_file(filename: str = 'config.yaml', max_levels_up: int = 3) -> Optional[Path]:
    """
    Search for config file in current directory and parent directories.
    
    Args:
        filename: Name of config file to find
        max_levels_up: Maximum number of parent directories to check
    
    Returns:
        Path to config file if found, None otherwise
    """
    current = Path.cwd()
    
    # First check if config exists in expected structure from current directory
    expected_path = current / 'customfunctions' / 'files' / filename
    if expected_path.is_file():
        return expected_path
        
    # Then check parent directories
    for _ in range(max_levels_up):
        # Check for config in customfunctions/files structure
        config_path = current / 'customfunctions' / 'files' / filename
        if config_path.is_file():
            return config_path
            
        # Also check for direct config.yaml in case structure is different
        direct_path = current / filename
        if direct_path.is_file():
            return direct_path
            
        current = current.parent
        
    return None


# %% ../nbs/01_common.ipynb 10
def get_config_path(snowflake_extracted_path: str = '/tmp/customfunctions') -> Path:
    """
    Determine the configuration file path based on environment.
    
    Args:
        snowflake_extracted_path: Path where Snowflake extracts files
    
    Returns:
        Path object pointing to config file
    """
    if is_snowflake_environment():
        # Snowflake environment logic remains the same
        import_dir = Path(sys._xoptions['snowflake_import_directory'])
        zip_file_path = import_dir / "customfunctions.zip"
        
        if not Path(snowflake_extracted_path).exists():
            try:
                with zipfile.ZipFile(zip_file_path, 'r') as myzip:
                    myzip.extractall(snowflake_extracted_path)
            except Exception as e:
                logging.error(f"Failed to extract ZIP file: {e}")
                raise
                
        return Path(snowflake_extracted_path) / 'customfunctions/files/config.yaml'
    else:
        # Local environment - search for config file
        config_path = find_config_file()
        if config_path is None:
            # If not found, return a default path for consistent error messaging
            return Path.cwd() / 'customfunctions' / 'files' / 'config.yaml'
        return config_path


# %% ../nbs/01_common.ipynb 12
def load_config(config_path: Path) -> Dict:
    """
    Load configuration from YAML file with error handling.
    
    Args:
        config_path: Path to configuration file
    
    Returns:
        Dictionary containing configuration
    """
    try:
        if config_path.is_file():
            with open(config_path, 'r') as file:
                config = yaml.safe_load(file)
                logging.info(f"Successfully loaded configuration from {config_path}")
                return config or {}
        else:
            logging.warning(f"Configuration file '{config_path}' not found. Using empty configuration.")
            return {}
    except Exception as e:
        logging.error(f"Error reading configuration file: {e}")
        return {}
