"""Helps Manage Snowflake Connection"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_functions.ipynb.

# %% ../nbs/02_functions.ipynb 3
from __future__ import annotations
from .common import print_hello

# %% auto 0
__all__ = ['hello_function']

# %% ../nbs/02_functions.ipynb 4
def hello_function(name: str) -> str:
    return print_hello(name)
